# Generated by Django 5.2.4 on 2025-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="password",
            field=models.CharField(default="ranxi", max_length=64),
            preserve_default=False,
        ),
    ]
