services:
  yumoback:
    image: yunximoran/yumoback
    build:
      context: .
      dockerfile: ./services/yumoback/.dockerfile
    prots:
      - 8000:8000
    
    networks:
      - core
      - database

  yumoviews:
    image: yunximoran/yumoviews
    build:
      context: .
      dockerfile: ./services/yumoviews/.dockerfile

    ports:
     - 8080:8080

    networks:
      - core

  redis:
    image: redis:latest
    ports:
      - 6389:6379

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306

cap_add:
  - ALL

networks:
  core:
    driver: custom-driver-1
  
  database:
    driver: custom-driver-2
    driver_opts:
      foo: "1"
      bar: "2"


