services:
  yumo:
    image: yumo
    build:
      context: .
      dockerfile: .dockerfile
    prots:
      - 8000:8000
      - 8080:8080

    networks:
      - core
      - database

  redis:
    image: redis:latest
    ports:
      - 6389:6379
    
    networks:
      - database

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306

    networks:
      - database

cap_add:
  - ALL

networks:
  core:
    driver: custom-driver-1
  
  database:
    driver: custom-driver-2
    driver_opts:
      foo: "1"
      bar: "2"


