channels:
  - conda-force
  - defaults
dependencies:
  - python=3.12.9
  - django=5.2.4
  - django-cors-headers=4.7.0
  - uvicorn=0.35.0
  - channels=4.3.0
  - websockets=15.0.1
  - requests=2.32.4
  - redis=3.5.3
  - pymysql=1.1.1
  - psutil=7.0.0